# Form implementation generated from reading ui file 'gui_gpt_keyboard.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *


class Keyboard_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi()
        self.setWindowFlags(QtCore.Qt.WindowType.WindowStaysOnTopHint)
        self.show()

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(275, 285)
        self.setMinimumSize(QtCore.QSize(275, 285))
        self.setMaximumSize(QtCore.QSize(275, 285))
        self.centralwidget = QtWidgets.QWidget(parent=self)
        self.centralwidget.setObjectName("centralwidget")
        self.keySequenceEdit = QtWidgets.QKeySequenceEdit(parent=self.centralwidget)
        self.keySequenceEdit.setGeometry(QtCore.QRect(120, 40, 113, 21))
        self.keySequenceEdit.setObjectName("keySequenceEdit")
        self.keySequenceEdit_2 = QtWidgets.QKeySequenceEdit(parent=self.centralwidget)
        self.keySequenceEdit_2.setGeometry(QtCore.QRect(120, 80, 113, 21))
        self.keySequenceEdit_2.setObjectName("keySequenceEdit_2")
        self.keySequenceEdit_3 = QtWidgets.QKeySequenceEdit(parent=self.centralwidget)
        self.keySequenceEdit_3.setGeometry(QtCore.QRect(120, 120, 113, 21))
        self.keySequenceEdit_3.setObjectName("keySequenceEdit_3")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 80, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 40, 81, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(35, 160, 81, 16))
        self.label_4.setObjectName("label_4")
        self.keySequenceEdit_4 = QtWidgets.QKeySequenceEdit(parent=self.centralwidget)
        self.keySequenceEdit_4.setGeometry(QtCore.QRect(120, 160, 113, 21))
        self.keySequenceEdit_4.setObjectName("keySequenceEdit_4")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(190, 220, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 275, 22))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("MainWindow", "답변 창 띄우기"))
        self.label_2.setText(_translate("MainWindow", "답변 창 닫기"))
        self.label_3.setText(_translate("MainWindow", " 음성녹음 시작"))
        self.label_4.setText(_translate("MainWindow", "프로그램 종료"))
        self.pushButton.setText(_translate("MainWindow", "저장"))


