# Form implementation generated from reading ui file 'gui_gpt_hyperparameter.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtWidgets
from PyQt6.QtWidgets import *
from optiondata import Option_data
from PyQt6.QtGui import *
from signalManager import SignalManager
import sys


class Parameter_MainWindow(QWidget):
    def __init__(self):
        super().__init__()

        self.option_data = Option_data()
        self.optionSignals = SignalManager().optionSignals

        self.setupUi()
        self.setWindowFlags(QtCore.Qt.WindowType.WindowStaysOnTopHint)
        self.show()

    def setupUi(self):
        self.setObjectName("Form")
        self.resize(240, 159)
        self.setMinimumSize(QtCore.QSize(240, 159))
        self.setMaximumSize(QtCore.QSize(240, 159))
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(60, 30, 31, 16))
        self.label.setObjectName("label")
        self.label.setText(str(self.option_data.temperature))
        self.lineEdit = QtWidgets.QLineEdit(self)
        self.lineEdit.setGeometry(QtCore.QRect(90, 30, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setText(str(self.option_data.temperature))
        self.lineEdit.setValidator(QDoubleValidator(0,10,1,self))
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 71, 20))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 70, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setText(str(self.option_data.max_tokens))
        self.lineEdit_2.setValidator(QIntValidator(self))
        self.pushButton_2 = QtWidgets.QPushButton(self)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 120, 75, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.savebutton_clicked)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "온도"))
        self.label_2.setText(_translate("Form", "길이 패널티"))
        self.pushButton_2.setText(_translate("Form", "저장"))

    #저장버튼 클릭 이벤트
    def savebutton_clicked(self):
        self.option_data.temperature = self.lineEdit.text()
        self.option_data.max_tokens = self.lineEdit_2.text()
        print("save hyperparameter")
        self.option_data.save_option()
        self.optionSignals.changed_parameter.emit()
        self.close()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Option = Parameter_MainWindow()
    sys.exit(app.exec())
