# Form implementation generated from reading ui file 'gui_gpt_keyboard.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *
from signalManager import SignalManager
from optiondata import Option_data
import sys


class Keyboard_MainWindow(QWidget):
    def __init__(self):
        super().__init__()
        self.option_data = Option_data()
        self.optionSignals = SignalManager().optionSignals

        self.setupUi()
        self.setWindowFlags(QtCore.Qt.WindowType.WindowStaysOnTopHint)
        self.show()

    def setupUi(self):
        self.setObjectName("Form")
        self.resize(306, 313)
        self.setMinimumSize(QtCore.QSize(306, 313))
        self.setMaximumSize(QtCore.QSize(306, 313))
        self.checkBox1_1 = QtWidgets.QCheckBox(self)
        self.checkBox1_1.setGeometry(QtCore.QRect(120, 30, 41, 20))
        self.checkBox1_1.setObjectName("checkBox1_1")
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.checkBox1_3 = QtWidgets.QCheckBox(self)
        self.checkBox1_3.setGeometry(QtCore.QRect(230, 30, 51, 20))
        self.checkBox1_3.setObjectName("checkBox1_3")
        self.checkBox1_2 = QtWidgets.QCheckBox(self)
        self.checkBox1_2.setGeometry(QtCore.QRect(180, 30, 41, 20))
        self.checkBox1_2.setObjectName("checkBox1_2")
        self.keySequenceEdit = QtWidgets.QKeySequenceEdit(self)
        self.keySequenceEdit.setGeometry(QtCore.QRect(120, 50, 151, 21))
        self.keySequenceEdit.setObjectName("keySequenceEdit")
        self.checkBox2_1 = QtWidgets.QCheckBox(self)
        self.checkBox2_1.setGeometry(QtCore.QRect(120, 90, 41, 20))
        self.checkBox2_1.setObjectName("checkBox2_1")
        self.checkBox2_3 = QtWidgets.QCheckBox(self)
        self.checkBox2_3.setGeometry(QtCore.QRect(230, 90, 51, 20))
        self.checkBox2_3.setObjectName("checkBox2_3")
        self.keySequenceEdit_2 = QtWidgets.QKeySequenceEdit(self)
        self.keySequenceEdit_2.setGeometry(QtCore.QRect(120, 110, 151, 21))
        self.keySequenceEdit_2.setObjectName("keySequenceEdit_2")
        self.checkBox2_2 = QtWidgets.QCheckBox(self)
        self.checkBox2_2.setGeometry(QtCore.QRect(180, 90, 41, 20))
        self.checkBox2_2.setObjectName("checkBox2_2")
        self.keySequenceEdit_3 = QtWidgets.QKeySequenceEdit(self)
        self.keySequenceEdit_3.setGeometry(QtCore.QRect(120, 170, 151, 21))
        self.keySequenceEdit_3.setObjectName("keySequenceEdit_3")
        self.checkBox3_3 = QtWidgets.QCheckBox(self)
        self.checkBox3_3.setGeometry(QtCore.QRect(230, 150, 51, 20))
        self.checkBox3_3.setObjectName("checkBox3_3")
        self.checkBox3_2 = QtWidgets.QCheckBox(self)
        self.checkBox3_2.setGeometry(QtCore.QRect(180, 150, 41, 20))
        self.checkBox3_2.setObjectName("checkBox3_2")
        self.checkBox3_1 = QtWidgets.QCheckBox(self)
        self.checkBox3_1.setGeometry(QtCore.QRect(120, 150, 41, 20))
        self.checkBox3_1.setObjectName("checkBox3_1")
        self.keySequenceEdit_4 = QtWidgets.QKeySequenceEdit(self)
        self.keySequenceEdit_4.setGeometry(QtCore.QRect(120, 230, 151, 21))
        self.keySequenceEdit_4.setObjectName("keySequenceEdit_4")
        self.checkBox4_3 = QtWidgets.QCheckBox(self)
        self.checkBox4_3.setGeometry(QtCore.QRect(230, 210, 51, 20))
        self.checkBox4_3.setObjectName("checkBox4_3")
        self.checkBox4_2 = QtWidgets.QCheckBox(self)
        self.checkBox4_2.setGeometry(QtCore.QRect(180, 210, 41, 20))
        self.checkBox4_2.setObjectName("checkBox4_2")
        self.checkBox4_1 = QtWidgets.QCheckBox(self)
        self.checkBox4_1.setGeometry(QtCore.QRect(120, 210, 41, 20))
        self.checkBox4_1.setObjectName("checkBox4_1")
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignTrailing | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self)
        self.label_5.setGeometry(QtCore.QRect(20, 160, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignTrailing | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self)
        self.label_6.setGeometry(QtCore.QRect(20, 220, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignTrailing | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.pushButton_2 = QtWidgets.QPushButton(self)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 270, 75, 24))
        self.pushButton_2.setMinimumSize(QtCore.QSize(75, 0))
        self.pushButton_2.setObjectName("pushButton_2")

        self.keySequenceEdit.setKeySequence(self.option_data.pressing_mic_key)
        self.keySequenceEdit_2.setKeySequence(self.option_data.show_content_key)
        self.keySequenceEdit_3.setKeySequence(self.option_data.copy_key)
        self.keySequenceEdit_4.setKeySequence(self.option_data.quit_key)

        self.pushButton_2.clicked.connect(self.savebutton_clicked)


        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "KEY 지정"))
        self.checkBox1_1.setText(_translate("Form", "Ctrl"))
        self.label_3.setText(_translate("Form", " 음성녹음 시작"))
        self.checkBox1_3.setText(_translate("Form", "Shift"))
        self.checkBox1_2.setText(_translate("Form", "Alt"))
        self.checkBox2_1.setText(_translate("Form", "Ctrl"))
        self.checkBox2_3.setText(_translate("Form", "Shift"))
        self.checkBox2_2.setText(_translate("Form", "Alt"))
        self.checkBox3_3.setText(_translate("Form", "Shift"))
        self.checkBox3_2.setText(_translate("Form", "Alt"))
        self.checkBox3_1.setText(_translate("Form", "Ctrl"))
        self.checkBox4_3.setText(_translate("Form", "Shift"))
        self.checkBox4_2.setText(_translate("Form", "Alt"))
        self.checkBox4_1.setText(_translate("Form", "Ctrl"))
        self.label_4.setText(_translate("Form", "답변 창 띄우기/닫기"))
        self.label_5.setText(_translate("Form", "답변 복사"))
        self.label_6.setText(_translate("Form", "프로그램 종료"))
        self.pushButton_2.setText(_translate("Form", "저장"))

        self.setcheckbox()

    def setcheckbox(self):
        if self.checkBox1_1.text() == self.option_data.pressing_mic_key_combination:
            self.checkBox1_1.setChecked(True)
        if self.checkBox1_2.text() == self.option_data.pressing_mic_key_combination:
            self.checkBox1_2.setChecked(True)
        if self.checkBox1_3.text() == self.option_data.pressing_mic_key_combination:
            self.checkBox1_3.setChecked(True)

        if self.checkBox2_1.text() == self.option_data.show_content_key_combination:
            self.checkBox2_1.setChecked(True)
        if self.checkBox2_2.text() == self.option_data.show_content_key_combination:
            self.checkBox2_2.setChecked(True)
        if self.checkBox2_3.text() == self.option_data.show_content_key_combination:
            self.checkBox2_3.setChecked(True)

        if self.checkBox3_1.text() == self.option_data.copy_key_combination:
            self.checkBox3_1.setChecked(True)
        if self.checkBox3_2.text() == self.option_data.copy_key_combination:
            self.checkBox3_2.setChecked(True)
        if self.checkBox3_3.text() == self.option_data.copy_key_combination:
            self.checkBox3_3.setChecked(True)

        if self.checkBox4_1.text() == self.option_data.quit_key_combination:
            self.checkBox4_1.setChecked(True)
        if self.checkBox4_2.text() == self.option_data.quit_key_combination:
            self.checkBox4_2.setChecked(True)
        if self.checkBox4_3.text() == self.option_data.quit_key_combination:
            self.checkBox4_3.setChecked(True)

        self.checkBox1_1.pressed.connect(self.clickedcheck_1)
        self.checkBox1_2.pressed.connect(self.clickedcheck_1)
        self.checkBox1_3.pressed.connect(self.clickedcheck_1)

        self.checkBox2_1.pressed.connect(self.clickedcheck_2)
        self.checkBox2_2.pressed.connect(self.clickedcheck_2)
        self.checkBox2_3.pressed.connect(self.clickedcheck_2)

        self.checkBox3_1.pressed.connect(self.clickedcheck_3)
        self.checkBox3_2.pressed.connect(self.clickedcheck_3)
        self.checkBox3_3.pressed.connect(self.clickedcheck_3)

        self.checkBox4_1.pressed.connect(self.clickedcheck_4)
        self.checkBox4_2.pressed.connect(self.clickedcheck_4)
        self.checkBox4_3.pressed.connect(self.clickedcheck_4)

    #저장버튼 클릭 이벤트
    def savebutton_clicked(self):
        self.option_data.pressing_mic_key = self.keySequenceEdit.keySequence().toString()
        self.option_data.show_content_key = self.keySequenceEdit_2.keySequence().toString()
        self.option_data.copy_key = self.keySequenceEdit_3.keySequence().toString()
        self.option_data.quit_key = self.keySequenceEdit_4.keySequence().toString()
        if self.checkBox1_1.isChecked():
            self.option_data.pressing_mic_key_combination = self.checkBox1_1.text()
        elif self.checkBox1_2.isChecked():
            self.option_data.pressing_mic_key_combination = self.checkBox1_2.text()
        elif self.checkBox1_3.isChecked():
            self.option_data.pressing_mic_key_combination = self.checkBox1_3.text()

        if self.checkBox2_1.isChecked():
            self.option_data.show_content_key_combination = self.checkBox2_1.text()
        elif self.checkBox2_2.isChecked():
            self.option_data.show_content_key_combination = self.checkBox2_2.text()
        elif self.checkBox2_3.isChecked():
            self.option_data.show_content_key_combination = self.checkBox2_3.text()

        if self.checkBox3_1.isChecked():
            self.option_data.copy_key_combination = self.checkBox3_1.text()
        elif self.checkBox3_2.isChecked():
            self.option_data.copy_key_combination = self.checkBox3_2.text()
        elif self.checkBox3_3.isChecked():
            self.option_data.copy_key_combination = self.checkBox3_3.text()

        if self.checkBox4_1.isChecked():
            self.option_data.quit_key_combination = self.checkBox4_1.text()
        elif self.checkBox4_2.isChecked():
            self.option_data.quit_key_combination = self.checkBox4_2.text()
        elif self.checkBox4_3.isChecked():
            self.option_data.quit_key_combination = self.checkBox4_3.text()

        self.option_data.save_option()
        self.optionSignals.changed_key.emit()
        print("save the key option")
        self.close()

    #체크박스 3개 중 하나만 체크상태 유지
    def clickedcheck_1(self):
        self.checkBox1_1.setChecked(False)
        self.checkBox1_2.setChecked(False)
        self.checkBox1_3.setChecked(False)

    def clickedcheck_2(self):
        self.checkBox2_1.setChecked(False)
        self.checkBox2_2.setChecked(False)
        self.checkBox2_3.setChecked(False)

    def clickedcheck_3(self):
        self.checkBox3_1.setChecked(False)
        self.checkBox3_2.setChecked(False)
        self.checkBox3_3.setChecked(False)

    def clickedcheck_4(self):
        self.checkBox4_1.setChecked(False)
        self.checkBox4_2.setChecked(False)
        self.checkBox4_3.setChecked(False)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Option = Keyboard_MainWindow()
    sys.exit(app.exec())
